/**************************************************************/
/****************** Name	: MOHAMED ELSAYED *****************/
/****************** Date	: 24/1/2021       *****************/
/****************** Version : 1.0V            *****************/
/****************** SWC		: MD              *****************/
/**************************************************************/
#ifndef MD_CONFIG_H
#define MD_CONFIG_H


/*SELECT CLCD Pins FROM OPTION:
*	GPIO_PORTA,GPIO_PIN0
*	GPIO_PORTA,GPIO_PIN1
*	GPIO_PORTA,GPIO_PIN2
*	GPIO_PORTA,GPIO_PIN3
*	GPIO_PORTA,GPIO_PIN4
*	GPIO_PORTA,GPIO_PIN5
*	GPIO_PORTA,GPIO_PIN6
*	GPIO_PORTA,GPIO_PIN7
*	GPIO_PORTA,GPIO_PIN8
*	GPIO_PORTA,GPIO_PIN9
*	GPIO_PORTA,GPIO_PIN10
*	GPIO_PORTA,GPIO_PIN11
*	GPIO_PORTA,GPIO_PIN12
*	GPIO_PORTA,GPIO_PIN13
*	GPIO_PORTA,GPIO_PIN14
*	GPIO_PORTA,GPIO_PIN15
*	GPIO_PORTB,GPIO_PIN0
*	GPIO_PORTB,GPIO_PIN1
*	GPIO_PORTB,GPIO_PIN5
*	GPIO_PORTB,GPIO_PIN6
*	GPIO_PORTB,GPIO_PIN7
*	GPIO_PORTB,GPIO_PIN8
*	GPIO_PORTB,GPIO_PIN9
*	GPIO_PORTB,GPIO_PIN10
*	GPIO_PORTB,GPIO_PIN11
*	GPIO_PORTB,GPIO_PIN12
*	GPIO_PORTB,GPIO_PIN13
*	GPIO_PORTB,GPIO_PIN14
*	GPIO_PORTB,GPIO_PIN15
*	GPIO_PORTC,GPIO_PIN0
*	GPIO_PORTC,GPIO_PIN1
*	GPIO_PORTC,GPIO_PIN2
*	GPIO_PORTC,GPIO_PIN3
*	GPIO_PORTC,GPIO_PIN4
*	GPIO_PORTC,GPIO_PIN5
*	GPIO_PORTC,GPIO_PIN6
*	GPIO_PORTC,GPIO_PIN7
*	GPIO_PORTC,GPIO_PIN8
*	GPIO_PORTC,GPIO_PIN9
*	GPIO_PORTC,GPIO_PIN10
*	GPIO_PORTC,GPIO_PIN11
*	GPIO_PORTC,GPIO_PIN12
*	GPIO_PORTC,GPIO_PIN13
*	GPIO_PORTC,GPIO_PIN14
*	GPIO_PORTC,GPIO_PIN15
*/
#define MD_u8_IN0_PIN	   GPIO_PORTB,GPIO_PIN12
#define MD_u8_IN1_PIN      GPIO_PORTB,GPIO_PIN13
#define MD_u8_IN2_PIN      GPIO_PORTB,GPIO_PIN14
#define MD_u8_IN3_PIN      GPIO_PORTB,GPIO_PIN15





#endif
