/**************************************************************/
/****************** Name	: Mohamed Elsayed *****************/
/****************** Date	: 15/9/2021       *****************/
/****************** Version : 1.0V            *****************/
/****************** SWC		: RCC             *****************/
/**************************************************************/
#ifndef RCC_CONFIG_H
#define RCC_CONFIG_H



/********** SELECT SYTEM CLK FROM THIS OPTION:
     *	RCC_HSI_CLK
 	 *	RCC_HSE_CLK
 	 *	RCC_PLL_CLK
 */
#define RCC_SYSTEM_CLK  RCC_HSI_CLK



#if RCC_SYSTEM_CLK == RCC_PLL_CLK

	/********** SELECT PLL CLK SOURCE FROM THIS OPTION:
	     *	RCC_PLL_SOURCE_FROM_HSI_DIVIDED_BY2
	 	 *	RCC_PLL_SOURCE_FROM_HSE_DIVIDED_BY2
	 	 *	RCC_PLL_SOURCE_FROM_HSE
	 */
     #define  RCC_PLL_CLK_SOURCE	RCC_PLL_SOURCE_FROM_HSI_DIVIDED_BY2

	/********** SELECT PLL MUL FACTOR FROM THIS OPTION:
		     *	RCC_PLL_MUL_X4
		 	 *	RCC_PLL_MUL_X5
		 	 *	RCC_PLL_MUL_X6
             *	RCC_PLL_MUL_X7
		 	 *	RCC_PLL_MUL_X8
		 	 *	RCC_PLL_MUL_X9
		 	 *	RCC_PLL_MUL_X6POINT5
    */
    #define RCC_PLL_MUL_FACTOR 	 RCC_PLL_MUL_X4
#endif






/********** SELECT RCC_ADC_PRESCALER FROM THIS OPTION:
	     *	RCC_ADC_PRESCALER_DIVIDED_BY2
	 	 *	RCC_ADC_PRESCALER_DIVIDED_BY4
	 	 *	RCC_ADC_PRESCALER_DIVIDED_BY6
	 	 *	RCC_ADC_PRESCALER_DIVIDED_BY8
	 */
#define RCC_ADC_PRESCALER 	RCC_ADC_PRESCALER_DIVIDED_BY2




/********** SELECT RCC_APB2_PRESCALER FROM THIS OPTION:
	     *	RCC_APB2_PRESCALER_NOT_DIVIDED
	 	 *	RCC_APB2_PRESCALER_DIVIDED_BY2
	 	 *	RCC_APB2_PRESCALER_DIVIDED_BY4
	 	 *	RCC_APB2_PRESCALER_DIVIDED_BY8
	 	 *	RCC_APB2_PRESCALER_DIVIDED_BY16
	 */
#define RCC_APB2_PRESCALER	RCC_APB2_PRESCALER_NOT_DIVIDED







/********** SELECT RCC_APB1_PRESCALER FROM THIS OPTION:
	     *	RCC_APB1_PRESCALER_NOT_DIVIDED
	 	 *	RCC_APB1_PRESCALER_DIVIDED_BY2
	 	 *	RCC_APB1_PRESCALER_DIVIDED_BY4
	 	 *	RCC_APB2_PRESCALER_DIVIDED_BY8
	 	 *	RCC_APB2_PRESCALER_DIVIDED_BY16
	 */
#define RCC_APB1_PRESCALER		RCC_APB1_PRESCALER_NOT_DIVIDED







/********** SELECT RCC_AHP_PRESCALER FROM THIS OPTION:
	     *	RCC_AHP_PRESCALER_NOT_DIVIDED
	 	 *	RCC_AHP_PRESCALER_DIVIDED_BY2
	 	 *	RCC_AHP_PRESCALER_DIVIDED_BY4
	 	 *	RCC_AHP_PRESCALER_DIVIDED_BY8
	 	 *	RCC_AHP_PRESCALER_DIVIDED_BY16
	 	 *	RCC_AHP_PRESCALER_DIVIDED_BY64
	 	 *	RCC_AHP_PRESCALER_DIVIDED_BY128
	 	 *	RCC_AHP_PRESCALER_DIVIDED_BY256
	 	 *	RCC_AHP_PRESCALER_DIVIDED_BY512
	 */
#define RCC_AHP_PRESCALER    RCC_AHP_PRESCALER_NOT_DIVIDED




/********** SELECT RCC_MCO_CLK_OUTPUT FROM THIS OPTION:
	     *	RCC_MCO_NO_OUTPUT_CLK
	 	 *	RCC_MCO_SYSTEM_CLK
	 	 *	RCC_MCO_HSI_CLK
	 	 *	RCC_MCO_HSE_CLK
	 	 *	RCC_MCO_PLL2_CLK
	 	 *	RCC_MCO_PLL3_CLK_DIVIDED_BY2
	 	 *	RCC_MCO_EXT1_FOR_ETHERNET_CLK
	 	 *	RCC_MCO_PLL3_CLK
	 	 */
#define RCC_MCO_CLK_OUTPUT RCC_MCO_NO_OUTPUT_CLK;



#endif
